MAX_VALUE = 999
MIN_VALUE = 0
MIN_VALUE_MESSAGE = f'The value is less than {MIN_VALUE}'
MAX_VALUE_MESSAGE = f'The value is higher than {MAX_VALUE}'
OUT_RANGE_MESSAGE = f"The value is out range. {MIN_VALUE}-{MAX_VALUE}"
INVALID_RANGE_MESSAGE = f"Invalid range"
VALIDATE_INTEGER_MESSAGE = 'The passed arg is not an integer'
NEGATIVE_RANGE_MESSAGE = "Not allowed negative values as range"
GRATER_COUNT = "greater_count"
LESS_COUNT = "less_count"
